export const teamMembers = [
  {
    id: "shanjay",
    name: "Shanjay",
    fullName: "Shanjay Akash T",
    role: "Founder & Leading Director",
    department: "Executive",
    location: "Chennai, India",
    image: "/shanjay pic.jpeg",
    coverImage: "/blog-cloud.png",
    color: "#5B4DFF",
    glow: "rgba(91, 77, 255, 0.5)",
    bio: "Founder and Leading Director of Akronix, Shanjay leads the company with a strong vision for scalable digital ecosystems.",
    longBio: "From ideation to execution, he has built Akronix into a platform that empowers businesses through SaaS, innovation, and strategic growth. His focus lies in creating future-ready solutions that bridge technology and business impact.",
    skills: ["Visionary Leadership", "Platform Architecture", "SaaS Innovation", "Strategic Execution", "Product Growth", "Full-Stack Engineering"],
    tagline: "\"Engineering the backbone of next-generation digital businesses.\"",
    socials: {
      instagram: "https://instagram.com/__mr.sanch__",
      linkedin: "https://www.linkedin.com/in/shanjay-akash-t-238464323?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      twitter: "https://twitter.com/shanjay",
      email: "shanjay@akronix.org",
      website: "https://akronix.org",
    },
    stats: [
      { label: "Products Built", value: "10+" },
      { label: "Years Experience", value: "5" },
      { label: "Projects Delivered", value: "15+" },
      { label: "Vision", value: "Unlimited" },
    ],
    highlights: [
      { title: "Built Akronix from ground up", desc: "Architected and launched the Akronix platform ecosystem." },
      { title: "Vision-driven leadership", desc: "Driving SaaS, innovation, and scalable digital solutions." },
      { title: "Strategic execution expert", desc: "Leading cross-functional teams and product growth." },
    ],
  },
  {
    id: "bharath",
    name: "Bharath",
    fullName: "Bharath",
    role: "Co-Founder & Executive Officer",
    department: "Operations",
    location: "Chennai, India",
    image: "/bharath pic.jpeg",
    coverImage: "/blog-strategy.png",
    color: "#7DD3FC",
    glow: "rgba(125, 211, 252, 0.5)",
    bio: "Bharath plays a crucial role in business operations and strategic execution.",
    longBio: "As Co-Founder, he ensures smooth workflows, builds partnerships, and drives Akronix’s expansion. He executes vision with operational excellence.",
    skills: ["Business Ops", "Strategic Partnerships", "Growth Channels", "Operational Excellence", "Team Management"],
    tagline: "\"Executing vision with operational excellence.\"",
    socials: {
      instagram: "https://instagram.com/bharath",
      linkedin: "https://linkedin.com/in/bharath",
      twitter: "https://twitter.com/bharath",
      email: "bharath@akronix.org",
      website: "https://akronix.org",
    },
    stats: [
      { label: "Operations", value: "Leader" },
      { label: "Partnerships", value: "Strategic" },
      { label: "Expansion", value: "Business" },
      { label: "Execution", value: "Specialist" },
    ],
    highlights: [
      { title: "Business operations leader", desc: "Manages execution and company expansion." },
      { title: "Strategic partnerships", desc: "Builds collaborations and growth channels." },
      { title: "Operational excellence", desc: "Ensures smooth workflow across teams." },
    ],
  },
  {
    id: "listhiroger",
    name: "Listhiroger",
    fullName: "Listhiroger",
    role: "Co-Founder & Networking Head",
    department: "Infrastructure",
    location: "Chennai, India",
    image: "/listhi pic.jpeg",
    coverImage: "/blog-cloud.png",
    color: "#34D399",
    glow: "rgba(52, 211, 153, 0.5)",
    bio: "Listhiroger leads networking and infrastructure at Akronix.",
    longBio: "As Co-Founder, he ensures secure, scalable, and efficient system connectivity. He builds the backbone of connectivity and systems.",
    skills: ["Network Infrastructure", "System Connectivity", "Scalable Systems", "Security Architecture", "Technical Leadership"],
    tagline: "\"Building the backbone of connectivity and systems.\"",
    socials: {
      instagram: "https://instagram.com/listhiroger",
      linkedin: "https://linkedin.com/in/listhiroger",
      twitter: "https://twitter.com/listhiroger",
      email: "listhroger@akronix.org",
      website: "https://akronix.org",
    },
    stats: [
      { label: "Network", value: "Architect" },
      { label: "Infrastructure", value: "Expert" },
      { label: "System", value: "Security" },
      { label: "Tech", value: "Backbone" },
    ],
    highlights: [
      { title: "Networking infrastructure lead", desc: "Manages system connectivity and architecture." },
      { title: "Technical backbone", desc: "Ensures secure and scalable network systems." },
      { title: "Co-founder leadership", desc: "Drives technical vision and operations." },
    ],
  },
  {
    id: "vishal",
    name: "Vishal",
    fullName: "Vishal",
    role: "Technical Officer",
    department: "Technology",
    location: "Chennai, India",
    image: "/vishal pic.JPG",
    coverImage: "/blog-engineering.png",
    color: "#F08A8A",
    glow: "rgba(240, 138, 138, 0.5)",
    bio: "As Technical Officer, Vishal leads the engineering direction of Akronix, ensuring strong architecture and system reliability.",
    longBio: "His expertise helps align technology with business growth and product scalability. He drives technology with scalability and innovation.",
    skills: ["System Architecture", "Engineering Direction", "Infrastructure", "Scalability", "Reliability Engineering", "Tech Strategy"],
    tagline: "\"Driving technology with scalability and innovation.\"",
    socials: {
      instagram: "https://instagram.com/vxshal_xo",
      linkedin: "https://www.linkedin.com/in/vishal-maran-697103349/",
      twitter: "https://twitter.com/vishal",
      email: "vishal@akronix.org",
      website: "https://akronix.org",
    },
    stats: [
      { label: "System", value: "Architect" },
      { label: "Infrastructure", value: "Leader" },
      { label: "Solutions", value: "Scalable" },
      { label: "Strategy", value: "Tech Expert" },
    ],
    highlights: [
      { title: "Technology leadership", desc: "Oversees system architecture and engineering direction." },
      { title: "Infrastructure & scalability", desc: "Ensures performance and reliability across platforms." },
      { title: "Technical strategy execution", desc: "Aligns tech with business goals." },
    ],
  },
  {
    id: "pranav",
    name: "Pranav",
    fullName: "Pranav",
    role: "Chief Creative Officer (CCO)",
    department: "Design",
    location: "Chennai, India",
    image: "/pranav pic.jpeg",
    coverImage: "/blog-design.png",
    color: "#FBBF24",
    glow: "rgba(251, 191, 36, 0.5)",
    bio: "Pranav leads the creative direction at Akronix, shaping brand identity and user experience.",
    longBio: "His work ensures every product delivers a premium and engaging visual experience. He designs experiences that define brands.",
    skills: ["Creative Direction", "Brand Identity", "Visual Storytelling", "Design Innovation", "UI/UX Leadership", "Brand Experience"],
    tagline: "\"Designing experiences that define brands.\"",
    socials: {
      instagram: "https://instagram.com/__.pranzzz__",
      linkedin: "https://linkedin.com/in/pranav",
      twitter: "https://twitter.com/pranav",
      email: "pranav@akronix.org",
      website: "https://akronix.org",
    },
    stats: [
      { label: "Creative", value: "Director" },
      { label: "UI/UX", value: "Expert" },
      { label: "Brand", value: "Strategist" },
      { label: "Visual", value: "Innovator" },
    ],
    highlights: [
      { title: "Creative direction lead", desc: "Defines brand identity and visual storytelling." },
      { title: "Design innovation", desc: "Leads UI/UX and creative campaigns." },
      { title: "Brand experience builder", desc: "Ensures premium and consistent design output." },
    ],
  },
  {
    id: "sarvika",
    name: "Sarvika",
    fullName: "Sarvika",
    role: "Digital Marketing Lead & Account Manager",
    department: "Marketing",
    location: "Chennai, India",
    image: "/Sarvika pic.jpeg",
    coverImage: "/blog-strategy.png",
    color: "#F472B6",
    glow: "rgba(244, 114, 182, 0.5)",
    bio: "Sarvika leads digital marketing and client relationships at Akronix.",
    longBio: "She specializes in growth strategies, campaign optimization, and ensuring client success through data-driven marketing. She turns strategy into measurable growth.",
    skills: ["Growth Marketing", "Brand Visibility", "Lead Generation", "Account Management", "ROI Campaigns", "Market Strategy"],
    tagline: "\"Turning strategy into measurable growth.\"",
    socials: {
      instagram: "https://instagram.com/sarvika_166",
      linkedin: "https://www.linkedin.com/in/sarvika-k-ab74b3326",
      twitter: "https://twitter.com/sarvika",
      email: "sarvika@akronix.org",
      website: "https://akronix.org",
    },
    stats: [
      { label: "Growth", value: "Expert" },
      { label: "Client Success", value: "Manager" },
      { label: "Campaigns", value: "ROI Focused" },
      { label: "Brand Scaling", value: "Specialist" },
    ],
    highlights: [
      { title: "Growth marketing strategist", desc: "Drives brand visibility and lead generation." },
      { title: "Client relationship management", desc: "Handles accounts and ensures client success." },
      { title: "Campaign optimization expert", desc: "Focused on ROI-driven digital marketing." },
    ],
  },
  {
    id: "mareeswaran",
    name: "Mareeswaran",
    fullName: "Mareeswaran",
    role: "Editing & Designing Head",
    department: "Content & Design",
    location: "Chennai, India",
    image: "/Mareeswaran pic.jpeg",
    coverImage: "/blog-engineering.png",
    color: "#FB923C",
    glow: "rgba(251, 146, 60, 0.5)",
    bio: "Mareeswaran heads editing and design, delivering high-quality visual content.",
    longBio: "His expertise ensures every output is polished, engaging, and aligned with brand standards. He transforms ideas into compelling visuals.",
    skills: ["Content Production", "Video Editing", "Motion Graphics", "Visual Design", "Media Optimization", "Creative Execution"],
    tagline: "\"Transforming ideas into compelling visuals.\"",
    socials: {
      instagram: "https://instagram.com/mareeswaran",
      linkedin: "https://linkedin.com/in/mareeswaran",
      twitter: "https://twitter.com/mareeswaran",
      email: "mareeswaran@akronix.org",
      website: "https://akronix.org",
    },
    stats: [
      { label: "Visual", value: "Storytelling" },
      { label: "Editing", value: "Specialist" },
      { label: "Motion", value: "& Design" },
      { label: "Content", value: "Perfectionist" },
    ],
    highlights: [
      { title: "Content production expert", desc: "Handles editing, motion, and visual design." },
      { title: "Creative execution", desc: "Transforms ideas into high-quality visuals." },
      { title: "Media optimization", desc: "Ensures engaging and polished outputs." },
    ],
  },
  {
    id: "avanthika",
    name: "Avanthika",
    fullName: "Avanthika Pradeep",
    role: "Technical Member",
    department: "Development",
    location: "Chennai, India",
    image: "/avanthika pic.jpeg",
    coverImage: "/blog-cloud.png",
    color: "#60A5FA",
    glow: "rgba(96, 165, 250, 0.5)",
    bio: "A key technical contributor at Akronix, Avanthika focuses on backend development and scalable architectures.",
    longBio: "She plays a vital role in optimizing performance and ensuring seamless system functionality across platforms, building robust systems with precision and performance.",
    skills: ["Backend Development", "Scalable Architectures", "Code Optimization", "Problem Solving", "System Engineering"],
    tagline: "\"Building robust systems with precision and performance.\"",
    socials: {
      instagram: "https://www.instagram.com/avanthio_o?utm_source=qr&igsh=NzNjMzQ2dzVsdTU1",
      linkedin: "https://www.linkedin.com/in/avanthika-pradeep-90252b310?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      twitter: "https://twitter.com/avanthika",
      email: "avanthika@akronix.org",
      website: "https://akronix.org",
    },
    stats: [
      { label: "Backend", value: "Specialist" },
      { label: "Optimization", value: "Focus" },
      { label: "Code", value: "High Performance" },
      { label: "Learning", value: "Continuous" },
    ],
    highlights: [
      { title: "Core development contributor", desc: "Works on backend systems and scalable architectures." },
      { title: "Problem-solving mindset", desc: "Focused on clean, efficient code and performance." },
      { title: "Tech innovation support", desc: "Contributes to product engineering and improvements." },
    ],
  },
  {
    id: "dakshithaa",
    name: "Dakshithaa",
    fullName: "Dakshithaa",
    role: "Technical Member",
    department: "Development",
    location: "Chennai, India",
    image: "/team.png",
    coverImage: "/blog-ai.png",
    color: "#A78BFA",
    glow: "rgba(167, 139, 250, 0.5)",
    bio: "Dakshithaa contributes to development and system improvements through continuous innovation.",
    longBio: "She focuses on feature enhancement, debugging, and maintaining performance standards, ensuring Akronix systems are constantly improving.",
    skills: ["Feature Development", "System Support", "Debugging", "Optimization", "Continuous Improvement"],
    tagline: "\"Enhancing systems through continuous innovation.\"",
    socials: {
      instagram: "https://instagram.com/dakshithaa",
      linkedin: "https://linkedin.com/in/dakshithaa",
      twitter: "https://twitter.com/dakshithaa",
      email: "dakshithaa@akronix.org",
      website: "https://akronix.org",
    },
    stats: [
      { label: "Development", value: "Support" },
      { label: "Feature", value: "Enhancement" },
      { label: "Debugging", value: "Expert" },
      { label: "Performance", value: "Focus" },
    ],
    highlights: [
      { title: "Development contributor", desc: "Works on application features and modules." },
      { title: "System support", desc: "Assists in debugging and optimization." },
      { title: "Continuous improvement", desc: "Enhances product performance." },
    ],
  },
  {
    id: "suriyakrishna",
    name: "Suriyakrishna",
    fullName: "Suriyakrishna",
    role: "Designer",
    department: "Design",
    location: "Chennai, India",
    image: "/suriya krishna pic.jpeg",
    coverImage: "/blog-design.png",
    color: "#818CF8",
    glow: "rgba(129, 140, 248, 0.5)",
    bio: "Suriyakrishna contributes to UI/UX design, creating clean and user-friendly interfaces.",
    longBio: "His designs enhance usability and maintain visual consistency across products. He crafts intuitive and modern user interfaces for engaging experiences.",
    skills: ["UI/UX Design", "Modern Interfaces", "Visual Design", "Branding Support", "Design Consistency"],
    tagline: "\"Crafting intuitive and modern user interfaces.\"",
    socials: {
      instagram: "https://instagram.com/suriyakrishna",
      linkedin: "https://linkedin.com/in/suriyakrishna",
      twitter: "https://twitter.com/suriyakrishna",
      email: "suriyakrishna@akronix.org",
      website: "https://akronix.org",
    },
    stats: [
      { label: "UI/UX", value: "Designer" },
      { label: "Creative", value: "Thinker" },
      { label: "Interface", value: "Specialist" },
      { label: "Design", value: "Consistency" },
    ],
    highlights: [
      { title: "UI/UX contributor", desc: "Designs intuitive and modern interfaces." },
      { title: "Creative support", desc: "Assists in visual design and branding." },
      { title: "Design consistency", desc: "Maintains cohesive design language." },
    ],
  },
  {
    id: "madhumitha",
    name: "Madhumitha",
    fullName: "Madhumitha",
    role: "Non-Technical Member",
    department: "Operations Support",
    location: "Chennai, India",
    image: "/team.png",
    coverImage: "/blog-strategy.png",
    color: "#6EE7B7",
    glow: "rgba(110, 231, 183, 0.5)",
    bio: "Madhumitha supports team coordination and operational flow.",
    longBio: "She ensures seamless communication and contributes to efficient execution across departments, enabling smooth operations behind the scenes at Akronix.",
    skills: ["Operations Support", "Team Coordination", "Process Management", "Communication", "Execution Support"],
    tagline: "\"Enabling smooth operations behind the scenes.\"",
    socials: {
      instagram: "https://instagram.com/madhumitha",
      linkedin: "https://linkedin.com/in/madhumitha",
      twitter: "https://twitter.com/madhumitha",
      email: "madhumitha@akronix.org",
      website: "https://akronix.org",
    },
    stats: [
      { label: "Operations", value: "Support" },
      { label: "Team", value: "Coordination" },
      { label: "Process", value: "Management" },
      { label: "Workflow", value: "Efficiency" },
    ],
    highlights: [
      { title: "Operations support", desc: "Assists in coordination and workflow." },
      { title: "Team collaboration", desc: "Ensures smooth communication across departments." },
      { title: "Process management", desc: "Supports execution and delivery." },
    ],
  },
];

export type TeamMember = typeof teamMembers[0];
